baseURL = baseURL = "https://alb-kestrel.pages.dev/"
languageCode = "en-us"
title = "Alb Kestrel"
theme = "terminal"

[params]
  # The theme uses these for the main accent color
  themeColor = "red"
  contentTypeName = "posts"
  showThemeSwitcher = false

  # Branding & Identity
  logoText = "alb@albgamingpc:~$"
  logoHomeLink = "/"
  # Ensure favicon.png is in your /static folder
  avatar = "favicon.png"

  # This pulls your custom styling from assets/css/custom.css
  customCSS = ["css/custom.css"]

[params.twitter]
  site = "AlbKestrel"

[[menu.main]]
  name = "The Forge"
  url = "/forge"
  weight = 1

[[menu.main]]
  name = "The Bench"
  url = "/bench"
  weight = 2

[[menu.main]]
  name = "The Docs"
  url = "/posts"
  weight = 3
